version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      golang:
        patterns:
          - "*"
    cooldown:
      default-days: 7
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
